env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules: 
  no-var: 
    - error 
  quotes: 
    - error
    - single
  indent: 
    - warn
    - 4
  dot-notation:
    - off
  semi: 
    - off
  space-before-function-paren:
    - off
  no-undef:
    - off
  no-unused-vars:
    - off
  handle-callback-err:
    - off
  no-path-concat:
    - off
