env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - standard
parserOptions:
  ecmaVersion: 11
rules: 
  no-var: 
    - error 
  quotes: 
    - error
    - single
  indent: 
    - warn
    - 4
  dot-notation:
    - off
  semi: 
    - off
  space-before-function-paren:
    - off